#!/bin/sh

if [ ! -d ./bin ]; then
	mkdir bin
fi

wine ./native/UICC.exe markup.xml bin/markup.bml /header:bin/markup.h /res:bin/markup.rc
sed -i -e 's/.\\markup.h/.\/markup.h/g' ./bin/markup.rc

i686-w64-mingw32-windres ./bin/markup.rc ./bin/markup.o
i686-w64-mingw32-gcc -c test.c -o bin/test.o
i686-w64-mingw32-gcc ./bin/test.o ./bin/markup.o -o bin/test.exe -l ole32
